# Generated by Django 2.2.6 on 2019-10-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem_perfil',
            field=models.ImageField(upload_to='uploads/', verbose_name='Imagem'),
        ),
    ]
