# Generated by Django 2.2.6 on 2019-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_usuario_imagem_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('preco', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=1000, verbose_name='Link')),
            ],
        ),
    ]
