# Generated by Django 2.2.6 on 2019-11-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros_Comprar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('imagem', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=1000, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Carros_Diarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('imagem', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=1000, verbose_name='Link')),
            ],
        ),
        migrations.DeleteModel(
            name='Carros',
        ),
    ]
