# Generated by Django 2.2.6 on 2019-11-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191113_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros_comprar',
            name='ano',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ano'),
        ),
    ]
