# Generated by Django 2.2.7 on 2019-11-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_carros_comprar_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros_comprar',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
